drop table permissions cascade;
drop table usr cascade;
drop table doors_X_keyrings cascade;
drop table keyrings cascade;
drop table doors_X_systems cascade;
drop table doors cascade;
drop table systems cascade;
drop table signing_keys cascade;
drop table systems cascade;
