truncate table permissions cascade;
truncate table usr cascade;
truncate table doors_X_keyrings cascade;
truncate table keyrings cascade;
truncate table doors_X_systems cascade;
truncate table doors cascade;
truncate table systems cascade;
truncate table signing_keys cascade;
truncate table systems cascade;
